[package]
name = "marketplace-anchor"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "marketplace_anchor"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-spl/idl-build"]


[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
<<<<<<< HEAD
anchor-spl = "0.31.1"
=======
anchor-spl = "0.31.1"

>>>>>>> 7d4635442f40f50539cd576d00b545725e6ffe11
